name: New AZG Issue
description: Stwórz nowy report błędu
title:
labels:
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Sprawdź [Guideline](https://example.com) w celu uzyskania dodatkowych informacji na temat zgłaszania bug'ów w projekcie AZG
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Wpływ błędu na przebieg rozgrywki użytkownika końcowego
      options:
        - N/A
        - Sev0
        - Sev1
        - Sev2
        - Sev3
        - Sev4
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Wpływ błędu na pracę nad projektem
      options:
        - N/A
        - Prio0
        - Prio1
        - Prio2
        - Prio3
        - Prio4
    validations:
      required: true
  - type: dropdown
    id: blocker
    attributes:
      label: BLOCKER Status
      options:
        - N/A
        - None
        - Blocker
        - Conditional Blocker
        - Review Blocker
    validations:
      required: true
  - type: dropdown
    id: mainPath
    attributes:
      label: Main Path
      description: Is Issue affecting Main Path areas?
      options:
        - N/A
        - GLOBAL
        - Main Playthtough
        - Main System/Feature/Area
        - Main Side Activity
        - NO
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Affected Platforms
      multiple: true
      options:
        - N/A
        - UEE
        - Win10
    validations:
      required: true
  - type: dropdown
    id: components
    attributes:
      label: Affected Components
      description: Postaraj się wybrać tylko jeden component. Wybierz component nadrzędny, jeśli błąd występuje w kilku miejscach.
      multiple: true
      options:
        - N/A
        - AI behaviour (AI)
        - ThirdPersonExampleMap
        - MovementMechanics (MM)
        - (MM) Dynamic Running
        - (MM) Grapple Hook
        - (MM) Jumping And Dashing
        - (MM) Crouching And Sliding
        - (MM) Vaulting And Climbing
        - (MM) Wall Running
        - Level Design (LD)
        - (LD) ThirdPersonExampleMap
        - (LD) VFX
        - 3D Art (Art)
        - (Art) Enviroment
        - (Art) LOD
        - (Art) 3D Models
        - (Art) Materials
        - (Art) VFX
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Dokładny opis powstania błędu i jego objawy
      placeholder: Co? Gdzie? Kiedy? Tylko przetestowane i potwierdzone informacje.
  - type: textarea
    id: notes
    attributes:
      label: Additional Info
      description: Dodatkowe informacje - notatki, linki, możliwe powiązania, wyjaśnienia, opis obejścia, itp
      placeholder: podaj informacje w punktach
  - type: textarea
    id: reproSteps
    attributes:
      label: Steps to Reproduce
      placeholder: Podaj kroki w punktach
    validations:
      required: true
  - type: checkboxes
    id: review
    attributes:
      label: Additional Review
      description: Czy potrzebujesz dodatkowej pomocy w ocenie treści lub poprawności powyższego ticketu? Jeśli tak, zajmie się nim inny członek zespołu.
      options:
        - label: YES, please!
